### ISSUE TITLE
Automating the section table of contents (TOC)

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#10]
Is there any way to automate the construction of section TOC. Now it is done through SUMMARY.md which has to be updated manually. Previous versions of Gitbook had the option of automating this but I am not sure if there have been changes.  We had something like that implemented in the 2019 course material but that may be outdated now as gitbook has also evolved: https://github.com/microbiome/course_nijmegen2019

**Comment by TuomasBorman** [comment]
I tried to solve this with current approach, but I think it's not possible or at least it's not easily done. I think the easiest way is to use `bookdown` package like it was done in `nijmegen2019` material

I will do that tomorrow morning

**Comment by antagomir** [comment]
This is fine. We seem to have used bookdown also with `OMA` , and I did not find any obvious advantages for using gitbook over bookdown. Perhaps most of this is readily available by just modifying the material from OMA. Even automating the conversion through Github Actions?

**Comment by TuomasBorman** [comment]
Solved
