### ISSUE TITLE
Hiding sections

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#21]
Is there a way to hide sections from the sidebar menu? I would like to keep the beta diversity Aitchison examples as additional material that I could add during the course, or by providing a link.

**Comment by TuomasBorman** [comment]
It is possible by adding `{.unlisted .unnumbered}` to the header, and I tested it and it works. https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html

Another option is to move the example to the file that already contains extra material `misc.Rmd`
