### ISSUE TITLE
Community typing

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#22]
This is advanced material, and I noticed that these examples are entirely missing from OMA. 

Let us move the [section on community typing](https://microbiome.github.io/course_2021_radboud/community-typing.html) from course material to the [dedicated section that is already in OMA](https://microbiome.github.io/OMA/microbiome-community.html#community-typing) but is missing content.

After moving the material, add link to the community typing section in the end of course material section on beta diversity.

I propose that @ChouaibB does this and @tvborm will check review the changes.

**Comment by TuomasBorman** [comment]
There is link to OMA book. When OMA's changes are ready the link needs to be modified so that it leads to the new community typing section

**Comment by ChouaibB** [comment]
Yes, I kept only the link to the book as a whole, expecting changes later.
