### ISSUE TITLE
Information missing from PDF version 

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/course_2021_radboud#23]
I think it would be nice to have also PDF version, if someone wants to download the material. PDF version can be opened from the top of html version (pdf icon). 

However, some code and tables are too wide, so that they don't fit to page. html version is on higher priority, so it's better to not make any modifications directly to the code, because that would modify also the html version. 

So, **if we want also the pdf version,** is there any options to modify only the pdf version, so that it would contain all the information? Maybe some parameters to `_output.yml` file like `gitbook` has? 

-Tuomas

**Comment by antagomir** [comment]
Good question - no immediate answer here. 

Is there anything in the material cited in [OMA #21](https://github.com/microbiome/OMA/issues/21)

**Comment by ChouaibB** [comment]
> I think it would be nice to have also PDF version, if someone wants to download the material. PDF version can be opened from the top of html version (pdf icon).
> 
> However, some code and tables are too wide, so that they don't fit to page. html version is on higher priority, so it's better to not make any modifications directly to the code, because that would modify also the html version.
> 
> So, **if we want also the pdf version,** is there any options to modify only the pdf version, so that it would contain all the information? Maybe some parameters to `_output.yml` file like `gitbook` has?
> 
> -Tuomas

I'll take a look
