### ISSUE TITLE
Links to be checked

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#30]
Got this report: when we showed the instructions, one link turned out broken: https://microbiome.github.io/course_2021_radboud/install.html

**Comment by TuomasBorman** [comment]
That link is in `02-start.Rmd`. Installing is moved to `02-start.Rmd,` and `install.Rmd/install.html `is deleted. I can remove the link

**Comment by TuomasBorman** [comment]
Solved
