### ISSUE TITLE
New automated book doesn't contain pdf version

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/course_2021_radboud#50]
New automated book doesn't contain pdf version. OMA doesn't contain that either. Is it possible to add that or is it possible remove pdf icon?

**Comment by antagomir** [comment]
I think it is possible to generate this automatically as part of Github Actions workflow. Do you like to give a try to see how it works?

**Comment by TuomasBorman** [comment]
I can check it

**Comment by TuomasBorman** [comment]
Solved
