### ISSUE TITLE
Citation and solutions problem

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/course_2021_radboud#54]
Hi,

I noticed that

1. Exercise solutions' html versions do not work. Should there be html versions? 

2. Citation in the last page is weird. I think it is done automatically, but I'm not sure where, in Github Action?
![image](https://user-images.githubusercontent.com/60338854/126607814-7582d177-ca43-429b-b0f3-bd4900e75e8e.png)

3. `10 Study material` still includes `10.2 Example solutions` subchapter even though there is already chapter `12 Exercise solutions`. Subchapter should be deleted?

-Tuomas

**Comment by antagomir** [comment]
1. No need now, lets fix for some next course where we use this as template
2. Citation can also be fixed for next ones, I think this goes for now
3. Yes Please fix

**Comment by TuomasBorman** [comment]
1. Removed links that did not work
2. No changes
3. `10.2 Example solutions` subchapter removed
