### ISSUE TITLE
Add question / example on TSE -> phyloseq conversion

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#8]
Important as there are still many tools that work with phyloseq. 

@HenrikEckermann could you make sure if both our demo data sets (open and proprietary one) can converted to phyloseq object? We could add an example Rmd file in the training material so that it is available as a model solution if someone needs it and cannot solve on his/her own.

**Comment by antagomir** [comment]
Can this be closed, all ok now? @HenrikEckermann

**Comment by HenrikEckermann** [comment]
Yes can be closed as I performed that transform in the diffab section. We can add more comprehensive examples in the OMA book as soon as we made the function work also at higher taxonomic ranks.
