### ISSUE TITLE
Additional resources section

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2021_radboud#9]
Can we add the following links in material.md (I will then pick these up and use in some other parts of the text also). Some of this you may readily find from the OMA book introduction section.

- SummarizedExperiment: link to the R/Bioconductor project page, and to the original publication
- TreeSummarizedExperiment: link to the R/Bioconductor project page, and to the original publication
- SingleCellExperiment: link to the R/Bioconductor project page, and to the original publication

**Comment by TuomasBorman** [comment]
Added links to material.md
